services:
  bot:
    build: .
    container_name: vodka-bot
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN} # Portainer will inject this from its UI
      - WELCOME_CHANNEL_ID=${WELCOME_CHANNEL_ID}
      - SECRET_ROLE=${SECRET_ROLE}
      - OWNER_ID=${OWNER_ID}
      - GUILD_ID=${GUILD_ID}
      - SUGGESTION_CHANNEL_ID=${SUGGESTION_CHANNEL_ID}
    volumes:
      - ./data:/app/data
